@extends('errors.layout')
@section('title', 'Permintaan Tidak Valid')
@section('code', '400')
@section('heading', 'Permintaan Tidak Valid')
@section('message', 'Permintaan yang kamu kirimkan tidak dapat diproses. Pastikan data yang kamu masukkan sudah benar.')
