@extends('errors.layout')
@section('title', 'Halaman Tidak Ditemukan')
@section('code', '404')
@section('heading', 'Halaman Tidak Ditemukan')
@section('message', 'Halaman yang kamu cari tidak tersedia atau sudah dipindahkan. Periksa kembali alamat yang kamu masukkan.')
